[WIP] Roles and Registration
Horizontal-org/shira-api pull request #27
Opened 2024-10-28 22:18 UTC by juandans01

2024-11-29 18:19 UTC, ValbuenaG requested changes
great job @juandans01! lot of things done. Let's just fix some error handling to keep consistence with the codebase. 

let's also not forget to add a try/catch for every async operation. 

Otherwise the code is perfect!

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/confirm-registration.auth.service.ts
> +    const registration = await this.regRepo.findOneOrFail({ where: {
let's add a catch here to handle the errors

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/confirm-registration.auth.service.ts
> +    if (compareAsc(expiresAt, new Date()) === -1) {
why are we using `compareAsc` here? could we use a native js comparison?

```
private checkRegistrationExpired(expiresAt: Date): void {
  if (expiresAt.getTime() < new Date().getTime()) {
    throw new UnauthorizedException();
  }
}
```

this should work and it's cleaner but do let me know if I'm missing something

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/confirm-registration.auth.service.ts
> +    const spaceDto = new CreateSpaceDto()
spaceDto isn't use right? let's use it in the `createSpaceService` below or remove it

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/submit-registration.auth.service.ts
> +
let's remove these spaces 😬

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/submit-registration.auth.service.ts
> +    await this.regRepo.save(registration)
let's do this async operation inside a try catch and handle the errors

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/validate-registration.auth.service.ts
> +  async execute(data: RegisterAuthDto): Promise<boolean> {
what do you think of adding a Promise.all here?

it should look like this:

```
const [passphraseTaken, user, spaceTaken] = await Promise.all([
    this.checkPassphrase.execute(data.passphrase),
    this.findUsername.execute(data.email),
    this.checkSpace.execute(data.spaceName)
  ]);    
```

then we just check each variable to check if is taken

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/auth/services/validate-registration.auth.service.ts
> +  async execute(data: RegisterAuthDto): Promise<boolean> {
the main goal of this is increase the performance validating in parallel

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/check.passphrase.service copy.ts
> +  async execute (passphrase: string) {
what happen if the passphrase is nil/undefined? let's add that validation

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/check.passphrase.service copy.ts
> +    const entity = await this.passphraseRepo.findOne({ where: {
let's handle the errors in case the entity is not found

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/check.passphrase.service copy.ts
> +import * as crypto from 'crypto'
let's remove this since we are not using it

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/check.passphrase.service copy.ts
> +import { ICreatePassphraseService } from '../interfaces/services/create.passphrase.service.interface';
same with this method

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/check.passphrase.service.ts
> +import { Injectable } from '@nestjs/common';
what is the original method? let's keep just one and remove the "copy" from the file naming

2024-11-29 18:19 UTC, ValbuenaG commented on src/modules/passphrase/services/create.passphrase.service.ts
> +    const passphraseEntities = await this.passphraseRepo.save(passphrases)
error handling here

2024-11-29 18:21 UTC, ValbuenaG commented on src/modules/passphrase/services/use.passphrase.service.ts
> +  async execute (code: string, usedBy: string) {
https://github.com/Horizontal-org/shira-api/pull/27#discussion_r1863817590

2024-11-29 18:21 UTC, ValbuenaG commented on src/modules/space/services/check.space.service.ts
> +  async execute (name: string) {
https://github.com/Horizontal-org/shira-api/pull/27#discussion_r1863817590

2024-11-29 18:21 UTC, ValbuenaG commented on src/modules/space/services/create.space.service.ts
> +  async execute (createSpaceDto: CreateSpaceDto) {
https://github.com/Horizontal-org/shira-api/pull/27#discussion_r1863817590

2025-01-29 21:57 UTC, juandans01 commented on src/modules/auth/services/validate-registration.auth.service.ts
> +  async execute(data: RegisterAuthDto): Promise<boolean> {
even thought i do agree that it would improve performance i don't think it would apply here since we need for this things to not be in parallel for security reasons, the order is specific for that reason

2025-01-29 21:58 UTC, juandans01 commented
most of feedback addressed. the one thing i'm not sure about is to add a try/catch for every ".save" the expection is going to exist if that fails and it's going to stop execution, so i don't think a custom specific expection is needed on those scenarios

2025-01-30 14:58 UTC, merged